# tasks file for ubuntu-2004-apache-mod-php
---
- name: apache | vhosts | create
  template:
    src: "etc/apache2/sites-available/{{ item.template.file }}"
    dest: "/etc/apache2/sites-available/{{ item.name }}"
  with_items: "{{ ubuntu_2004_apache_mod_php_apache_vhosts_present | default([]) }}"
  notify: reload apache2

- name: apache | vhosts | create (html) directory
  file:
    path: "{{ item.html_dir.dest | default((item.base_dir.dest | default('/home/' ~ item.username | default('root'))) ~ '/public_html') }}/"
    state: directory
    owner: "{{ item.html_dir.owner | default(item.base_dir.owner) | default(item.username) | default('root') }}"
    group: "{{ item.html_dir.group | default(item.html_dir.owner) | default(item.base_dir.group) | default(item.base_dir.owner) | default(item.username) | default('root') }}"
    mode: "{{ item.html_dir.mode | default(item.base_dir.mode) | default('0755') }}"
  with_items: "{{ ubuntu_2004_apache_mod_php_apache_vhosts_present | default([]) }}"
  when: item.html_dir.managed | default(true)

- name: apache | vhosts | create (log) directory
  file:
    path: "{{ item.log_dir.dest | default((item.base_dir.dest | default('/home/' ~ item.username | default('root'))) ~ '/log') }}/"
    state: directory
    owner: "{{ item.log_dir.owner | default(item.base_dir.owner) | default(item.username) | default('root') }}"
    group: "{{ item.log_dir.group | default(item.log_dir.owner) | default(item.base_dir.group) | default(item.base_dir.owner) | default(item.username) | default('root') }}"
    mode: "{{ item.log_dir.mode | default(item.base_dir.mode) | default('0755') }}"
  with_items: "{{ ubuntu_2004_apache_mod_php_apache_vhosts_present | default([]) }}"
  when: item.log_dir.managed | default(true)

- name: apache | vhosts | create .env file
  template:
    src: "var/www/localdomain/localhost/.env.j2"
    dest: "{{ item.base_dir.dest | default('/home/' ~ item.username) }}/.env"
  with_items: "{{ ubuntu_2004_apache_mod_php_apache_vhosts_present | default([]) }}"
  when: item.set_env | default([]) | length > 0
