# tasks file for ubuntu-2004-apache-mod-php
---
- name: apache | mods | remoteip | update /etc/apache2/mods-available/remoteip.conf
  ansible.builtin.template:
    src: etc/apache2/mods-available/remoteip.conf.j2
    dest: /etc/apache2/mods-available/remoteip.conf
  notify: reload apache2
