# tasks file for ubuntu-2004-apache-mod-php
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_2004_apache_mod_php_apache_dependencies }}"

- name: install | additional
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_2004_apache_mod_php_apache_install }}"
