# tasks file for ubuntu-2004-apache-mod-php
---
- name: apache | mods | prefork | update /etc/apache2/mods-available/mpm_prefork.conf
  ansible.builtin.template:
    src: etc/apache2/mods-available/mpm_prefork.conf.j2
    dest: /etc/apache2/mods-available/mpm_prefork.conf
    mode: '644'
  notify: reload apache2
