# tasks file for ubuntu-2004-apache-mod-php
---
- name: php | mods | install
  ansible.builtin.apt:
    name: "{{ ubuntu_2004_apache_mod_php_php_mods_dependencies[item] | default([]) }}"
  with_items: "{{ ubuntu_2004_apache_mod_php_php_mods_enabled }}"
  notify: reload apache2
